#!/usr/bin/env python3
"""
install_git_hook.py — Install a post-commit git hook for QuillAI wiki updates.

Run this once from the repo root:

    python -m core.install_git_hook          # install
    python -m core.install_git_hook --remove # uninstall
    python -m core.install_git_hook --check  # check status

The hook calls `python -m core.wiki_hook` which does a headless incremental
wiki update for files changed in the last commit.  This covers the case where
the developer commits from a terminal outside QuillAI, where WikiWatcher is
not running.

If a hook already exists, the QuillAI hook is appended / prepended rather
than replacing it.
"""

from __future__ import annotations

import argparse
import os
import stat
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Hook content
# ---------------------------------------------------------------------------

_HOOK_MARKER_START = "# >>> QuillAI wiki hook >>>"
_HOOK_MARKER_END = "# <<< QuillAI wiki hook <<<"

_HOOK_SNIPPET = """\
{start}
# Auto-generated by QuillAI install_git_hook.py — do not edit this block.
if command -v python3 &>/dev/null; then
    python3 -m core.wiki_hook --repo "$(git rev-parse --show-toplevel)" &
fi
{end}
""".format(start=_HOOK_MARKER_START, end=_HOOK_MARKER_END)

_HOOK_SHEBANG = "#!/bin/sh\n"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_repo_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print("ERROR: Not inside a git repository.", file=sys.stderr)
        sys.exit(1)
    return Path(result.stdout.strip())


def _hook_path(repo_root: Path) -> Path:
    return repo_root / ".git" / "hooks" / "post-commit"


def _is_installed(hook_path: Path) -> bool:
    if not hook_path.exists():
        return False
    return _HOOK_MARKER_START in hook_path.read_text(encoding="utf-8")


def _install(repo_root: Path) -> None:
    hook = _hook_path(repo_root)
    hooks_dir = hook.parent
    hooks_dir.mkdir(parents=True, exist_ok=True)

    if hook.exists():
        existing = hook.read_text(encoding="utf-8")
        if _HOOK_MARKER_START in existing:
            print("QuillAI hook already installed.")
            return
        # Append to existing hook
        new_content = existing.rstrip("\n") + "\n\n" + _HOOK_SNIPPET
    else:
        new_content = _HOOK_SHEBANG + "\n" + _HOOK_SNIPPET

    hook.write_text(new_content, encoding="utf-8")
    # Ensure executable
    current = hook.stat().st_mode
    hook.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"✓ QuillAI post-commit hook installed at {hook}")
    print("  Wiki pages will auto-update on each commit (background process).")


def _remove(repo_root: Path) -> None:
    hook = _hook_path(repo_root)
    if not hook.exists():
        print("No post-commit hook found.")
        return

    content = hook.read_text(encoding="utf-8")
    if _HOOK_MARKER_START not in content:
        print("QuillAI hook not found in post-commit hook.")
        return

    # Strip the block between markers (inclusive)
    lines = content.splitlines(keepends=True)
    out: list[str] = []
    inside = False
    for line in lines:
        if _HOOK_MARKER_START in line:
            inside = True
        if not inside:
            out.append(line)
        if _HOOK_MARKER_END in line:
            inside = False

    new_content = "".join(out).rstrip("\n") + "\n"

    # If only the shebang remains, remove the file entirely
    if new_content.strip() in ("", "#!/bin/sh"):
        hook.unlink()
        print(f"✓ post-commit hook removed entirely (was only QuillAI content).")
    else:
        hook.write_text(new_content, encoding="utf-8")
        print(f"✓ QuillAI block removed from {hook}")


def _check(repo_root: Path) -> None:
    hook = _hook_path(repo_root)
    if _is_installed(hook):
        print(f"✓ QuillAI hook is installed at {hook}")
    else:
        print(f"✗ QuillAI hook is NOT installed (checked {hook})")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Manage QuillAI post-commit wiki hook."
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--remove", action="store_true", help="Remove the hook")
    group.add_argument("--check", action="store_true", help="Check hook status")
    args = parser.parse_args()

    repo_root = _find_repo_root()

    if args.remove:
        _remove(repo_root)
    elif args.check:
        _check(repo_root)
    else:
        _install(repo_root)


if __name__ == "__main__":
    main()